// Generated by CoffeeScript 1.3.3

/*
 * Copyright (c) 2011, iSENSE Project. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer. Redistributions in binary
 * form must reproduce the above copyright notice, this list of conditions and
 * the following disclaimer in the documentation and/or other materials
 * provided with the distribution. Neither the name of the University of
 * Massachusetts Lowell nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
*/


(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.Bar = (function(_super) {

    __extends(Bar, _super);

    function Bar(canvas) {
      this.canvas = canvas;
    }

    Bar.prototype.analysisType = "Max";

    Bar.prototype.buildOptions = function() {
      var categoryIndex, fieldIndex, groupIndex, groupName, options;
      Bar.__super__.buildOptions.call(this);
      this.chartOptions;
      return $.extend(true, this.chartOptions, {
        chart: {
          type: "column"
        },
        title: {
          text: "Bar"
        },
        xAxis: {
          categories: (function() {
            var _i, _len, _ref, _results;
            _ref = data.normalFields;
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              fieldIndex = _ref[_i];
              if ((__indexOf.call(globals.fieldSelection, fieldIndex) >= 0)) {
                _results.push(data.fields[fieldIndex].fieldName);
              }
            }
            return _results;
          })()
        }
      }, (function() {
        var _i, _len, _ref, _results;
        _ref = data.normalFields;
        _results = [];
        for (categoryIndex = _i = 0, _len = _ref.length; _i < _len; categoryIndex = ++_i) {
          fieldIndex = _ref[categoryIndex];
          _results.push((function() {
            var _j, _len1, _ref1, _results1;
            _ref1 = data.groups;
            _results1 = [];
            for (groupIndex = _j = 0, _len1 = _ref1.length; _j < _len1; groupIndex = ++_j) {
              groupName = _ref1[groupIndex];
              if (!((__indexOf.call(globals.groupSelection, groupIndex) >= 0) && (__indexOf.call(globals.fieldSelection, fieldIndex) >= 0))) {
                continue;
              }
              options = {
                data: [
                  {
                    x: categoryIndex,
                    y: data.getMax(fieldIndex, groupIndex)
                  }
                ],
                showInLegend: false,
                color: globals.colors[groupIndex % globals.colors.length],
                name: data.groups[groupIndex] + data.fields[fieldIndex].fieldName
              };
              _results1.push(this.chartOptions.series.push(options));
            }
            return _results1;
          }).call(this));
        }
        return _results;
      }).call(this));
    };

    Bar.prototype.drawAnalysisTypeControls = function() {
      var controls;
      controls = '<div id="AnalysisTypeControl" class="vis_controls">';
      controls += '<table class="vis_control_table"><tr><td class="vis_control_table_title">Analysis Type:</td></tr>';
      controls += '<tr><td><div class="vis_control_table_div">';
      controls += '<select id="drawAnalysisTypeSelector"><option>Max</option><option>Min</option><option>Mean</option></select>';
      controls += '</div></td></tr>';
      controls += '</table></div>';
      ($('#controldiv')).append(controls);
      return ($('#drawAnalysisTypeSelector')).change;
    };

    Bar.prototype.drawControls = function() {
      this.drawGroupControls();
      return this.drawAnalysisTypeControls();
    };

    Bar.prototype.update = function() {
      var fieldIndex, groupIndex, index, ser, _i, _j, _len, _ref, _ref1, _results;
      this.buildOptions();
      if (this.chart != null) {
        this.chart.destroy();
      }
      this.chart = new Highcharts.Chart(this.chartOptions);
      _ref = this.chart.series.slice(0, data.normalFields.length);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        ser = _ref[_i];
        index = data.normalFields[ser.index];
        if (__indexOf.call(globals.fieldSelection, index) >= 0) {
          ser.show();
        } else {
          ser.hide();
        }
      }
      ($('#' + this.canvas)).show();
      this.clearControls();
      this.drawControls();
      _results = [];
      for (index = _j = 0, _ref1 = this.chart.series.length - data.normalFields.length; 0 <= _ref1 ? _j < _ref1 : _j > _ref1; index = 0 <= _ref1 ? ++_j : --_j) {
        groupIndex = index % data.groups.length;
        fieldIndex = data.normalFields[Math.floor(index / data.groups.length)];
        if ((__indexOf.call(globals.groupSelection, groupIndex) >= 0) && (__indexOf.call(globals.fieldSelection, fieldIndex) >= 0)) {
          this.chart.series[index + data.normalFields.length].setVisible(true, false);
        } else {
          this.chart.series[index + data.normalFields.length].setVisible(false, false);
        }
        _results.push(this.chart.redraw());
      }
      return _results;
    };

    return Bar;

  })(BaseVis);

  globals.bar = new Bar('bar_canvas');

}).call(this);
