// Generated by CoffeeScript 1.3.3

/*
 * Copyright (c) 2011, iSENSE Project. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer. Redistributions in binary
 * form must reproduce the above copyright notice, this list of conditions and
 * the following disclaimer in the documentation and/or other materials
 * provided with the distribution. Neither the name of the University of
 * Massachusetts Lowell nor the names of its contributors may be used to
 * endorse or promote products derived from this software without specific
 * prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
*/


(function() {
  var _ref;

  if ((_ref = window.globals) == null) {
    window.globals = {};
  }

  globals.saveVis = function(title, desc, succCallback, failCallback) {
    var req, savedData;
    savedData = globals.serializeVis();
    return req = $.ajax({
      type: 'POST',
      url: "/actions/highvis.php",
      data: {
        action: "save",
        experiment_id: Number(data.experimentID),
        title: title,
        description: desc,
        data: savedData.data,
        globals: savedData.globals
      },
      success: function(msg) {
        if (!isNaN(Number(msg))) {
          return succCallback(msg);
        } else {
          return failCallback(msg);
        }
      }
    });
  };

  globals.verifyUser = function(succCallback, failCallback) {
    var req;
    return req = $.ajax({
      type: 'GET',
      url: "/actions/users.php",
      data: {
        action: "verify"
      },
      success: function(data) {
        if ((Number(data)) === 1) {
          return succCallback(data);
        } else {
          return failCallback(data);
        }
      }
    });
  };

  globals.savedVisDialog = function() {
    var formText;
    formText = "<div id=\"dialog-form\" title=\"Save Visualization\">\n\n    <form>\n    <fieldset>\n        <label for=\"title\">Title:</label>\n        <input type=\"text\" size=\"45 maxlength=\"64\" name=\"title\" id=\"savedVisTitle\" class=\"text ui-widget-content ui-corner-all\" /> <br> <span id=\"titleHint\" class=\"hint\"> </span> <br>\n        \n        <label for=\"desc\">Description:</label> <br>\n        <textarea type=\"text\" name=\"desc\" maxlength=\"512\" rows=\"10\" cols=\"50\" id=\"savedVisDesc\" class=\"text ui-widget-content ui-corner-all\" />\n        <br>\n    </fieldset>\n    </form>\n</div>";
    ($("#container")).append(formText);
    return ($("#dialog-form")).dialog({
      resizeable: false,
      autoOpen: true,
      height: 'auto',
      width: 'auto',
      modal: true,
      open: function() {
        return ($("#dialog-form form")).submit(function(evt) {
          this.parent().find("#dialog-form").trigger("click");
          return false;
        });
      },
      buttons: {
        Save: function() {
          var valid, _ref1;
          valid = true;
          ($('#dialog-form input')).removeClass('ui-state-error');
          ($('#dialog-form .hint')).text('');
          if (!((0 < (_ref1 = ($('#savedVisTitle')).val().length) && _ref1 <= 64))) {
            ($('#savedVisTitle')).addClass('ui-state-error');
            ($('#titleHint')).text('Title cannot be ommitted.');
            ($('#titleHint')).addClass('ui-state-highlight');
            setTimeout((function() {
              return ($('#titleHint')).removeClass('ui-state-highlight', 1500);
            }), 500);
            valid = false;
          }
          if (valid) {
            return globals.saveVis(($('#savedVisTitle')).val(), ($('#savedVisDesc')).val(), (function(v) {
              window.location = "../highvis.php?vid=" + v;
              return ($("#dialog-form")).dialog('close');
            }), (function(v) {
              return alert('Error:' + v);
            }));
          }
        }
      },
      close: function() {
        return ($('#dialog-form')).remove();
      }
    });
  };

}).call(this);
