// Generated by CoffeeScript 1.3.3
(function() {

  data.selector = function(fieldIndex, filterFunc) {
    var rawData;
    if (filterFunc == null) {
      filterFunc = function(dp) {
        return true;
      };
    }
    rawData = data.dataPoints.filter(filterFunc);
    return rawData.map(function(dp) {
      return dp[fieldIndex];
    });
  };

}).call(this);
